### ISSUE TITLE
Which repository membership model do we want to use?

### ISSUE THREAD

**Issue by adammontville** [opencybersecurityalliance/PACE#12]
We need to decide which membership model we want to use for the repository. Github provides a variety of roles (i.e. read, triage, write, maintain, admin, etc.). Do we want to create one or more teams?

This model should be documented to list maintainers and chairs as well.

**Comment by dlemire60** [comment]
The various roles and their permissions are documented here:  https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by dlemire60** [comment]
After some discussion on the [PACE mail list](https://lists.oasis-open-projects.org/g/oca-pace-wg/topics), I suggest the following:

1. Identify one or more sub-project leads for PACE. Right now that would be @adammontville  and **???**
2. Create a write team for each PACE-related repo (right now there’s just one), and give the sub-project leads the responsibility for identifying who should be on the write team
3. Be clear that either sub-project leads or the PGB have the authority to remove someone from the write team.

This is similar to the model OASIS uses for TC work product repos

**Comment by adammontville** [comment]
@dlemire60, thanks for looking into this. To clarify here, when you write sub-project you're talking about PACE as a sub-project to OCA. If my understanding is correct, that makes sense.

Then, do we want to create MAINTAINERS (example [here](https://github.com/eea-oasis/baseline/blob/master/MAINTAINERS.md)) and CONTRIBUTING (example [here](https://github.com/eea-oasis/baseline/blob/master/CONTRIBUTING.md)) files per Chet's suggestion on the mailing list?

**Comment by davaya** [comment]
Chet says: "We set the -write group to the Maintain role. We reserve Admin for staff. I believe we set the basic Member role to write.

I'm surprised that all members have the Write role, since Write allows pushing and merging, while Maintain is a superset but only allows trivial additional permissions: edit repo description, manage topics, enable wikis / restrict wiki editors, etc.  I don't think I can merge/push on repos where I am a member but not on the -write (role=Maintain) team.

I'd suggest
* all MAINTAINERS be on the -write team (anyone who self-nominates to be an active developer, not just Adam + 1),
* all other members and the public have role=Read

Anyone with the Read role can become a CONTRIBUTOR by submitting a contribution; there's no special team or role for contributors.  This implies that members not on the -write team do not have role=Write, which I believe is currently the case.  Validating individual and entity CLAs would have to be done, but the implementation does not involve GitHub roles.

**Comment by dlemire60** [comment]
> @dlemire60, thanks for looking into this. To clarify here, when you write sub-project you're talking about PACE as a sub-project to OCA. If my understanding is correct, that makes sense.

Yes:  Project = OCA; Sub-Projects = PACE, etc.

**Comment by sparrell** [comment]
Can I replay what I think got said above:
- project = OCA
   + subproject = PACE
      - repo = PACE (with potential for other repos under PACE at a later time)

I think the repo = subproject name will get confusing if we do have other repos. I hope we do have other repos (ie some open source software in addition to our documentation). Should we consider renaming the PACE repo something like PACE_ops?

**Comment by sparrell** [comment]
I suggest we have a process document for maintainers (ie those with write capability) to follow:
- all changes done as pull requests
- other than emergency cases, we have a two-person rule. Ie maintainer can not approve their own changes
- trivial editorial changes still follow the 2-person rule but don't require approval at a meeting (but do require reporting that it occurred at the next meeting)
- all other changes get approved at the weekly meeting (ie the "second person" is the group)
- periodically we make 'releases' or 'tags' with version numbers

**Comment by JasonKeirstead** [comment]
I would suggest that whatever you think today, you will end up needing many more repos later simply due to code mechanics.
 
To use Kestrel as an example - it has 5 repos currently already and is only 6 months old
kestrel-analytics
kestrel-lang
kestrel-jupyter
kestrel-huntbook
firepit
 
@sparrell Agreed with above but want to do this at an OCA level, its not just for PACE.

**Comment by sparrell** [comment]
Note the member model we use may be impacted by the collaborative model we use - see #17

**Comment by sparrell** [comment]
@JasonKeirstead - which membership model does stixshifter use? Ie who has write and how are changes approved? Ditto kestrel? Which collaborative development model does each use - fork-and-pull or shared-repo?

**Comment by adammontville** [comment]
During the 2022-01-10 meeting, we determined that PACE needs to write this information down in a CONTRIBUTING.md file, then the other projects can look at it and maybe emulate for up-leveling. They may come back with ideas/constraints/etc., but we don't want to block ourselves. Let's move ahead and adapt if we need to.

Same goes for how we manage maintainers on possible multiple PACE repositories - we'll defer deciding how that works until we need to.

Fork-and-pull model over shared

Admin is hands-off; only maintainers have direct capability

Contributors file needs to list actual maintainers - selected by acclimation at one of our meetings.

**Comment by dlemire60** [comment]
I've created PR #21 with an initial draft of CONTRIBUTING.md to capture the discussion from the 10 January meeting.  Please review and comment.
