### ISSUE TITLE
SBOM retrieval: use case and actuator profile

### ISSUE THREAD

**Issue by davaya** [opencybersecurityalliance/PACE#40]
PACE has a PCS, PES, and PAR, each with an interface as shown in the [architecture](https://github.com/opencybersecurityalliance/PACE/blob/main/docs/Arch/README.md).

Questions related to those interfaces are listed in the OpenC2 [SBOM Actuator Profile](https://github.com/oasis-tcs/openc2-ap-sbom/issues/38).  Should this issue be discussed under OpenC2 or PACE?

**Comment by sparrell** [comment]
My opinion is that PACE should set the requirements, particularly with use cases and examples; and that OpenC2 should worry the details of the command semantics/syntax. There were will grey areas of overlap, but hopefully there is enough cross-fertilization of membership so that won't be an problem.

**Comment by slarchacki22** [comment]
Discussed at 03/22/2022 PACE meeting and decision to close.
PACE will interact with OpenC2 to define requirements for actuator profiles.
